apiVersion: apps/v1
kind: Deployment
metadata:
  name: beds
  labels:
    app: beds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beds
  template:
    metadata:
      labels:
        app: beds
    spec:
      containers:
        - name: beds
          image: "username/beds:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
