server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: hospital
          uri: http://localhost:8082
          predicates:
            - Path=/hospitals/**, 
        - id: beds
          uri: http://localhost:8083
          predicates:
            - Path=/beds/**, 
        - id: patient
          uri: http://localhost:8084
          predicates:
            - Path=/patients/**, 
        - id: hospitalization
          uri: http://localhost:8085
          predicates:
            - Path=/hospitalizations/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: hospital
          uri: http://hospital:8080
          predicates:
            - Path=/hospitals/**, 
        - id: beds
          uri: http://beds:8080
          predicates:
            - Path=/beds/**, 
        - id: patient
          uri: http://patient:8080
          predicates:
            - Path=/patients/**, 
        - id: hospitalization
          uri: http://hospitalization:8080
          predicates:
            - Path=/hospitalizations/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
