---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
  labels:
    app: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
        - name: hospital
          image: username/hospital:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: beds
  labels:
    app: beds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beds
  template:
    metadata:
      labels:
        app: beds
    spec:
      containers:
        - name: beds
          image: username/beds:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
  labels:
    app: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: username/patient:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitalization
  labels:
    app: hospitalization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospitalization
  template:
    metadata:
      labels:
        app: hospitalization
    spec:
      containers:
        - name: hospitalization
          image: username/hospitalization:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: hospital
  labels:
    app: hospital
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hospital


---


apiVersion: v1
kind: Service
metadata:
  name: beds
  labels:
    app: beds
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: beds


---


apiVersion: v1
kind: Service
metadata:
  name: patient
  labels:
    app: patient
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: patient


---


apiVersion: v1
kind: Service
metadata:
  name: hospitalization
  labels:
    app: hospitalization
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hospitalization

