apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospitalization
  labels:
    app: hospitalization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospitalization
  template:
    metadata:
      labels:
        app: hospitalization
    spec:
      containers:
        - name: hospitalization
          image: "username/hospitalization:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
